[gcp][feat] Add metrics collection
someengineering/fixinventory pull request #2283
Opened 2024-11-20 17:36 UTC by 1101-1

# Description

## Services where metrics collection has completed:

- [x] Instance
- [x] Volume
- [x] Database
- [x] Load Balancers
- [x] Serverless

# Code of Conduct

By submitting this pull request, I agree to follow the [code of conduct](https://inventory.fix.security/code-of-conduct).

2024-11-25 13:56 UTC, aquamatthias commented on plugins/gcp/fix_plugin_gcp/resources/base.py
> +    def collect_usage_metrics(self, builder: GraphBuilder) -> List:  # type: ignore
Can we define the list type?

2024-11-25 13:56 UTC, aquamatthias commented on plugins/gcp/fix_plugin_gcp/resources/monitoring.py
> +                # "filter": None,
commented out on purpose?

2024-11-27 08:38 UTC, aquamatthias commented on plugins/gcp/fix_plugin_gcp/config.py
> +        default=64,
what is the reason for this change?

2024-11-27 08:38 UTC, aquamatthias commented on plugins/gcp/fix_plugin_gcp/resources/base.py
> +    stat_map: frozendict[str, StatName] = frozendict(
Is this a static map? Does it make sense to have it as property?

2024-11-27 09:22 UTC, 1101-1 commented on plugins/gcp/fix_plugin_gcp/config.py
> +        default=64,
to make it same as in azure and aws

2024-11-27 10:06 UTC, aquamatthias requested changes

2024-11-27 10:06 UTC, aquamatthias commented on plugins/gcp/fix_plugin_gcp/collector.py
> +                    monitoring.update_resource_metrics(resource, result)
No. This way, you fetch metrics one by one.
You should call this method, pass the resource and not wait for the result.
The called method can then spawn threads etc.

2024-11-27 15:48 UTC, aquamatthias submitted a review, later dismissed
LGTM - Thanks!

2024-11-28 15:26 UTC, aquamatthias commented on plugins/gcp/fix_plugin_gcp/resources/base.py
> +        return self.id.strip().split("/")[-1]
```suggestion
        return self.id..rsplit("/", maxsplit=1)[-1]
```

2024-11-28 16:06 UTC, aquamatthias submitted a review, later dismissed

2024-12-02 07:40 UTC, aquamatthias approved these changes

2024-12-04 09:02 UTC, merged